### ISSUE TITLE
How to share and keep synced code inside /app/public between php fpm and nginx container in k8s ?

### ISSUE THREAD

**Issue by kconde2** [sherifabdlnaby/kubephp#20]
I made this deployment.
I created a k8s cluster with one node locally on my computer.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-nginx
          image: my-backend_nginx
          imagePullPolicy: Always
          ports:
            - name: nginx
              containerPort: 8080
          env:
            - name: PHP_FPM_HOST
              value: 127.0.0.1
        - name: backend-php-fpm
          image: my-backend_php-fpm
          imagePullPolicy: Always
          ports:
            - name: php-fpm
              containerPort: 9000
          envFrom:
            - configMapRef:
                name: backend-configmap
```

When user upload files, they are stored into `/app/public/media` (not empty) under php-fpm container
My problem is that those files are not replicated inside nginx container under same path `/app/public/media` (empty).

Thanks in advance.
